// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drlmpffatkltykeatdgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybG1wZmZhdGtsdHlrZWF0ZGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzkyNDIsImV4cCI6MjA2NTIxNTI0Mn0.l34MXRzRwYfM4MygACbGONfyoFzHa6hwDgA2AmJUwLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);