
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxlqrxinpzvnuqksmffl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bHFyeGlucHp2bnVxa3NtZmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjA3ODQsImV4cCI6MjA2NDA5Njc4NH0.mM4C01Wa1RRyDxsOtZQraIikQvUUyGZ6479fhxkQokY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
